### PR TITLE
Bump go module version to v2

### PR DESCRIPTION
**Pull request by justinmanley**
Go modules with version >= 2.0.0 must have module names ending with `/v2` (or, for version `N`, `/vN`).

Without this, running `go get github.com/peak/s5cmd@v2.0.0` results in the following error:

```
go: github.com/peak/s5cmd@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/peak/s5cmd/v2")
```

This requirement is explained in greater detail in the [official golang wiki](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

### CODE REVIEW

**Comment by itay** [comment]
Any chance this is going to be approved/merged?

**Comment by igungor** [comment]
@justinmanley could you rebase your branch please?

**Comment by justinmanley** [comment]
@igungor rebased!

**Review by igungor — APPROVED** [review]

**Comment by justinmanley** [comment]
hi @ilkinulas! could you take a quick look at this when you get a chance?

**Review by ilkinulas — APPROVED** [review]

**Pull request merged**
