### PR TITLE
fix lost region

### PR DESCRIPTION
**Pull request by tombokombo**
Hi this PR fixes lost region, Options opts.region are used only internally for cp src dst region, there is no cmd flag for region,  so setSessionRegion is called for command like ls, run etc. If the region is set via env or config file is never used, func always fallback to aws-sdk s3manager.GetBucketRegion, but aws sdk will not recognize non aws regions like nl-ams (scaleway).

### CODE REVIEW

**Comment by tombokombo** [comment]
@igungor @seruman guys, could you please review this bugfix? Thanks.

**Comment by igungor** [comment]
Sorry for the late reply @tombokombo but I was on vacation. There're a couple of issues related with region-detection. To address them, there's an open ticket: https://github.com/peak/s5cmd/issues/320.

We're actively working on a pull-request to fix all of them I hope.

**Comment by tombokombo** [comment]
great, thx

**Comment by sonmezonur** [comment]
Closing this PR since https://github.com/peak/s5cmd/pull/331 addresses all region-related issues.

**Pull request closed without merging**
