### PR TITLE
Avoid setting rlimit on windows 

### PR DESCRIPTION
**Pull request by igungor**
Also update goreleaser.yml to compile binaries for Windows.

### CODE REVIEW

**Comment by seruman** [comment]
I've tried to run all tests on `Windows 10 Version 1803 (OS Build 17134.1488)` with `go1.14.3 windows/amd64
`

End-to-end tests fails with;
```
Command:  C:\Users\selman\AppData\Local\Temp\366358699\s5cmd --endpoint-url http://127.0.0.1:55259 ls s3://test-list-nonexisting-s-3-object-in-given-prefix/*/testfile*.txt
ExitCode: 127
Error:    exec: "C:\\Users\\selman\\AppData\\Local\\Temp\\366358699\\s5cmd": file does not exist
Stdout:   
Stderr:   
```

Seems like `exec.LookPath` on Windows expects executable file extensions.
https://github.com/golang/go/blob/master/src/os/exec/lp_windows.go#L59-L74

I've applied change below to run them;
```diff
diff --git a/e2e/util_test.go b/e2e/util_test.go
index b1eddfc..35aeb95 100644
--- a/e2e/util_test.go
+++ b/e2e/util_test.go
@@ -134,7 +134,7 @@ func goBuildS5cmd() func() {
                panic(err)
        }

-       s5cmdPath = filepath.Join(tmpdir, "s5cmd")
+       s5cmdPath = filepath.Join(tmpdir, "s5cmd.exe")

        workdir, err := os.Getwd()
        if err != nil {
```

It seems like Windows does not permit concurrent access to file, I think it's`s5cmd.exe` in this case
```
 TestMoveMultipleFilesToS3: mv_test.go:168: assertion failed: 
        Command:  C:\Users\selman\AppData\Local\Temp\890320039\s5cmd.exe --endpoint-url http://127.0.0.1:55815 mv C:\Users\selman\AppData\Local\Temp\test-move-multiple-files-to-s-3-125408426/* s3://test-move-multiple-files-to-s-3/
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   ERROR "mv C:\\Users\\selman\\AppData\\Local\\Temp\\test-move-multiple-files-to-s-3-125408426\\another_test_file.txt s3://test-move-multiple-files-to-s-3/another_test_file.txt": remove C:\Users\selman\AppData\Local\Temp\test-move-multiple-files-to-s-3-125408426\another_test_file.txt: The process cannot access the file because it is being used by another process.
        ERROR "mv C:\\Users\\selman\\AppData\\Local\\Temp\\test-move-multiple-files-to-s-3-125408426\\readme.md s3://test-move-multiple-files-to-s-3/readme.md": remove C:\Users\selman\AppData\Local\Temp\test-move-multiple-files-to-s-3-125408426\readme.md: The process cannot access the file because it is being used by another process.
        ERROR "mv C:\\Users\\selman\\AppData\\Local\\Temp\\test-move-multiple-files-to-s-3-125408426\\filename-with-hypen.gz s3://test-move-multiple-files-to-s-3/filename-with-hypen.gz": remove C:\Users\selman\AppData\Local\Temp\test-move-multiple-files-to-s-3-125408426\filename-with-hypen.gz: The process cannot access the file because it is being used by another process.
        ERROR "mv C:\\Users\\selman\\AppData\\Local\\Temp\\test-move-multiple-files-to-s-3-125408426\\testfile1.txt s3://test-move-multiple-files-to-s-3/testfile1.txt": remove C:\Users\selman\AppData\Local\Temp\test-move-multiple-files-to-s-3-125408426\testfile1.txt: The process cannot access the file because it is being used by another process.
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
```

and we have mixed path separators;
```
TestCopyMultipleLocalNestedFilesToS3: cp_test.go:2511: cp a\readme.md s3://bucket/prefix/a\readme.md
        cp a\file1.txt s3://bucket/prefix/a\file1.txt
        cp b\c\file2.txt s3://bucket/prefix/b\c\file2.txt
    TestCopyMultipleLocalNestedFilesToS3: cp_test.go:2522: assertion failed: error is not nil: prefix/a/readme.md: s3: no such key
--- FAIL: TestCopyMultipleLocalNestedFilesToS3 (0.28s)
```

```
TestRemoveLocalDirectory: rm_test.go:401: line 0: equals: (-want +got):
      string(
    - 	"rm testdir/file1.txt",
    + 	`rm testdir\file1.txt`,
      )
TestRemoveLocalDirectory: rm_test.go:401: line 1: equals: (-want +got):
      string(
    - 	"rm testdir/file2.txt",
    + 	`rm testdir\file2.txt`,
      )
TestRemoveLocalDirectory: rm_test.go:401: line 2: equals: (-want +got):
      string(
    - 	"rm testdir/readme.md",
    + 	`rm testdir\readme.md`,
      )
TestRemoveLocalDirectory: rm_test.go:401: rm testdir\file1.txt
    rm testdir\file2.txt
    rm testdir\readme.md
```

You can find both runs' output here: https://gist.github.com/seruman/3162fe1873905135ea5534135a37c839

**Comment by igungor** [comment]
> I've tried to run all tests on `Windows 10 Version 1803 (OS Build 17134.1488)` with `go1.14.3 windows/amd64 `

Thanks. Let's address those issues first, and make CI run the tests on Windows. After that, I'm going to merge this PR.

**Comment by sonmezonur** [comment]
I haven't tested but we may easily fix windows tests with [filepath.FromSlash()](https://golang.org/pkg/path/filepath/#FromSlash). We just need to call this function for each line on assertLines() function (https://github.com/peak/s5cmd/blob/master/e2e/util_test.go#L413).

**Comment by igungor** [comment]
> Thanks. Let's address those issues first, and make CI run the tests on Windows. After that, I'm going to merge this PR.

I'm gonna take this statement back as there are many changes required to address issues that are surfaced in CI jobs;  including CircleCI problems (suboptimal Windows support), s5cmd stdout assertions, and Windows-specific issues that I don't know how to fix yet.

I'm going to merge this PR as is (compiles on Windows, has all the basic functionality). After that, I'll open a new PR to try Github Actions. Github has better macOS and Windows support.

**Pull request merged**
