### PR TITLE
storage/s3: fix precedence of region detection

### LINKED ISSUE #320: Redesign region detection
We are using the following information to detect bucket region:
- AWS_REGION environtment variable
- `--source-region` and `--destination-region` options
- Region value returned from `head bucket` request

Document how and in which order  s5cmd uses these values.

### LINKED ISSUE #325: Error during uploads to Openstack SWIFT S3
Hi,

When I try to upload objects to our own Openstack SWIFT S3 setup I get the following error. 

AWS_ACCESS_KEY_ID=access_key AWS_SECRET_ACCESS_KEY=secret key AWS_REGION=NL ./s5cmd --endpoint-url https://my.endpoint cp /path/to/file s3://bucket 
ERROR "cp /path/to/file s3://bucket/file": AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'NL' status code: 400, request id: txb0926a6d6af64ec1b4056-0060eeb559, host id: txb0926a6d6af64ec1b4056-0060eeb559

This is with version 1.3.0. Using version 1.1.0 it just works. Somehow it seems that only us-east-1 is allowed.

Could this be fixed?

Btw. I am really impressed by the performance.

Cheers,

Ron

### PR DESCRIPTION
**Pull request by seruman**
Previously auto region detection would always override the region defined in SDK config which populated via `AWS_REGION/AWS_DEFAULT_REGION` or region in given profile with `AWS_PROFILE`.

https://github.com/peak/s5cmd/blob/02f63b3798aa5a2424867771308f67cec6fd3071/storage/s3.go#L822-L832

This was causing issues mainly on users of S3 compatible services returning empty response on `HeadBucket` request that's converted into `us-east-1` in `s3manager.GetBucketRegion()`([1](https://github.com/aws/aws-sdk-go/blob/b8fe768e4ce7f8f7c002bd7b27f4f5a8723fb1a5/service/s3/s3manager/bucket_region.go#L146), [2](https://github.com/aws/aws-sdk-go/blob/b8fe768e4ce7f8f7c002bd7b27f4f5a8723fb1a5/service/s3/bucket_location.go#L23-L32)) ; e.g #325, #354.

This PR makes changes to predecense of region detection as below;

1. `--source-region` or `--destination-region` flags of `cp` command.
2. `AWS_REGION` environment variable.
3. Region section of AWS profile.
4. Auto detection from bucket region (via `HeadBucket`).
5. `us-east-1` as default region.

Resolves #325, resolves #320.

Closes #317.

### CODE REVIEW

**Comment by Niek** [comment]
@igungor @sonmezonur @ilkinulas Can this PR be reviewed?

**Comment by seruman** [comment]
Hi @Niek, as this change breaks the usage of auto-region detection we plan to release it on v2.0.0 in the following months.

**Comment by igungor** [comment]
@seruman could you rebase and update the changelog?

**Review by igungor — APPROVED** [review]

**Comment by igungor** [comment]
I've removed Onur from the reviewers list. He is on "vacation" for a month 😄 . 🍸

**Review by aykutfarsak — APPROVED** [review]

**Pull request merged**
