### PR TITLE
Add steps for installation using MacPorts

### PR DESCRIPTION
**Pull request by manojkarthick**
Hi! I'm a macOS user and I noticed that this tool is available on Homebrew but was missing from MacPorts. So I took the liberty of adding the package. This PR updates the README with installation steps. 

Relevant links: 
* MacPorts: https://www.macports.org/
* Installation Config: https://github.com/macports/macports-ports/blob/master/net/s5cmd/Portfile

### CODE REVIEW

**Review by sonmezonur — APPROVED** [review]
@manojkarthick Hello! Thank you for your contribution.

**Comment by igungor** [comment]
Our release process (`goreleaser` under the hood) **automatically** creates tarballs, updates Docker images and brew formula. Unfortunately [it doesn't support `macports`](https://github.com/goreleaser/goreleaser/issues/1556). That's why it's missing from the readme. Also the fact that the whole team uses `brew` :)

I don't know much about `macports` but I see that `s5cmd` is in the index, so the Portfile needs to be updated after each release, right? I'm not sure we'd do that. If we merge this, we should mention that `macports` is not officially supported, so updates may fall behind.

**Comment by igungor** [comment]
>  If we merge this, we should mention that macports is not officially supported, so updates may fall behind.

Hi @manojkarthick. Is the above approach sound good to you? If so, would you update the readme please?

**Comment by manojkarthick** [comment]
> > If we merge this, we should mention that macports is not officially supported, so updates may fall behind.
> 
> Hi @manojkarthick. Is the above approach sound good to you? If so, would you update the readme please?

Sounds good @igungor - I've updated the PR with a note on support.

**Comment by igungor** [comment]
Thanks!

**Pull request merged**
