### PR TITLE
command/error: dont print cancelation errors

### LINKED ISSUE #117: Handle all cancelation errors
Canceling a copy operation prints context cancelation error even though we check explicitly.

### PR DESCRIPTION
**Pull request by igungor**
Fixes #117

### CODE REVIEW

**Comment by sonmezonur** [comment]
Still happening.
```
./s5cmd cp testfile1 s3://bucket/prefix/testfile1
^CERROR "cp testfile1 s3://bucket/prefix/testfile1": RequestCanceled: request context canceled caused by: context canceled
```

**Comment by igungor** [comment]
> Still happening.
> 
> ```
> ./s5cmd cp testfile1 s3://bucket/prefix/testfile1
> ^CERROR "cp testfile1 s3://bucket/prefix/testfile1": RequestCanceled: request context canceled caused by: context canceled
> ```

I tested this for ListBuckets call. Since Copy uses multierror or errorpkg.Error, it needs to be handled as well.

**Comment by igungor** [comment]
I can't reproduce the problem anymore @sonmezonur. Do you have a consistent repro?

**Comment by igungor** [comment]
ping @sonmezonur

**Comment by sonmezonur** [comment]
@igungor It does not log errors on download operations but for upload, I can reproduce the error:
First, create a sufficiently large temp file.
```
mkfile -n 1g temp_1GB_file
```

If you cancel immediately after starting the upload.
```
s5cmd cp temp_1GB_file s3://bucket/temp_file
^CERROR "cp testuplad.txt s3://bucket/temp_file": RequestCanceled: request context canceled caused by: context canceled
```
If you wait for a while, then cancel:
```
s5cmd cp temp_1GB_file s3://bucket/temp_file
MultipartUpload: upload multipart failed upload id: ... caused by: RequestCanceled: request context canceled caused by: context canceled
```

**Comment by igungor** [comment]
Thanks for the repro. Sent a fix. Could you test please?

**Comment by sonmezonur** [comment]
@igungor It is working now. Thanks

**Pull request merged**
