### PR TITLE
vendor: Update AWS SDK

### PR DESCRIPTION
**Pull request by matan129**
Hi, this is a simple change - I have a setup with AWS SSO, specifically `sso_session` ([docs](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html#:~:text=This%20results%20in%20creating%20the%20sso%2Dsession%20section%20and%20named%20profile%20in%20~/.aws/config%20that%20looks%20like%20the%20following%3A)).

It got implemented in the AWS Go SDK fairly recently https://github.com/aws/aws-sdk-go/pull/4885 - [v1.44.298](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.298)
 
Since it's just a patch version upgrade, it was just a simple matter of bumping the version.

Thanks

### CODE REVIEW

**Comment by tmehlinger** [comment]
Just ran into this myself. Please review and cut this into a new release.

**Comment by matan129** [comment]
Hi @embik , can we get this merged?

**Comment by matan129** [comment]
Hi @igungor, can we get this merged? Thanks :pray:

**Comment by billzhang3046** [comment]
Is there any update to this PR? Really looking forward to supporting S3 Express!

**Comment by matan129** [comment]
Hi @ahmethakanbesel, any change for getting it merged?

**Review by ahmethakanbesel — APPROVED** [review]

**Comment by denizsurmeli** [comment]
Closes #726.

**Comment by denizsurmeli** [comment]
Hi, thanks for your contribution. Can you please follow the [style guide](https://go.dev/wiki/CommitMessage) in the PR title, since the title will be the commit message in the master branch.

**Comment by matan129** [comment]
Done

**Comment by denizsurmeli** [comment]
Hi, with the following go build:
```
go version go1.22.1 darwin/arm64
```

When run 
```
go mod tidy && go mod vendor
```

The following diff occurs. 
```diff
diff --git a/go.sum b/go.sum
index cf4b72f..53f6cf4 100644
--- a/go.sum
+++ b/go.sum
@@ -1,6 +1,5 @@
 github.com/VividCortex/ewma v1.2.0 h1:f58SaIzcDXrSy3kWaHNvuJgJ3Nmz59Zji6XoJR/q1ow=
 github.com/VividCortex/ewma v1.2.0/go.mod h1:nz4BbCtbLyFDeC9SUHbtcT5644juEuWfUAUnGx7j5l4=
-github.com/aws/aws-sdk-go v1.44.256 h1:O8VH+bJqgLDguqkH/xQBFz5o/YheeZqgcOYIgsTVWY4=
 github.com/aws/aws-sdk-go v1.44.256/go.mod h1:aVsgQcEevwlmQ7qHE9I3h+dtQgpqhFB+i8Phjh7fkwI=
 github.com/aws/aws-sdk-go v1.44.298 h1:5qTxdubgV7PptZJmp/2qDwD2JL187ePL7VOxsSh1i3g=
 github.com/aws/aws-sdk-go v1.44.298/go.mod h1:aVsgQcEevwlmQ7qHE9I3h+dtQgpqhFB+i8Phjh7fkwI=
```

The same diff occurs with `go 1.19.1`. Can you please `go mod tidy && go mod vendor` and add the changes to the PR ? Thanks.

**Comment by matan129** [comment]
Fixed

**Review by ahmethakanbesel — APPROVED** [review]

**Review by denizsurmeli — APPROVED** [review]

**Review by ilkinulas — APPROVED** [review]

**Pull request merged**
