### PR TITLE
github: add Go 1.15.x to build/test jobs

### PR DESCRIPTION
**Pull request by igungor**

### CODE REVIEW

**Review by sonmezonur — APPROVED** [review]

**Comment by igungor** [comment]
ping @aykutfarsak @ilkinulas

**Comment by aykutfarsak** [comment]
@igungor it would be nice if we add a status badge to README.md:

```
![CI](https://github.com/peak/s5cmd/workflows/CI/badge.svg)
```

**Comment by igungor** [comment]
> @igungor it would be nice if we add a status badge to README.md:
> 
> ```
> CI
> ```

Personally I'm not very keen on status badges if they're not proven useful. I can still add if you (or others) want to see it on the readme.

**Comment by igungor** [comment]
> > @igungor it would be nice if we add a status badge to README.md:
> > ```
> > CI
> > ```
> 
> Personally I'm not very keen on status badges if they're not proven useful. I can still add if you (or others) want to see it on the readme.

We've talked about this w/ @aykutfarsak and decided to show this badge in the README. We don't allow any changes if it breaks CI checks. Showing a green CI status in the README has a positive impact on potential users of the project.

**Comment by igungor** [comment]
@aykutfarsak PTAL

**Review by aykutfarsak — APPROVED** [review]
LGTM

**Pull request merged**
