### PR TITLE
command: add --request-payer flag

### PR DESCRIPTION
**Pull request by Kirill888**
allow access to requester pays buckets, issue #297

### CODE REVIEW

**Review by sonmezonur — COMMENTED** [review]
Thanks for your contribution.

Some of the storage operations ( `Select()`, `Put()`, `Delete()` etc.) do not use `request-payer` option. Could you add this option to all S3 operations/functions?

**Comment by Kirill888** [comment]
> Some of the storage operations ( `Select()`, `Put()`, `Delete()` etc.) do not use `request-payer` option. Could you add this option to all S3 operations/functions?

@sonmezonur thanks for looking into this, I have added `RequestPayer` options to `Put()` and `Delete()`, but `Select()` doesn't seem to have that option strangely, it's certainly not exposed in the `SelectObjectContentInput` struct, and there is no mention of that option in [http api docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html) either.

**Review by sonmezonur — APPROVED** [review]

**Comment by sonmezonur** [comment]
@Kirill888 LGTM. Could you add an example for the usage of this option? Similar to [examples in ls command](https://github.com/peak/s5cmd/blob/master/command/ls.go#L40)

**Review by sonmezonur — APPROVED** [review]

**Review by ilkinulas — APPROVED** [review]

**Comment by sonmezonur** [comment]
@Kirill888 could you resolve conflicts in your branch?

**Comment by sonmezonur** [comment]
Sorry, 9d494116475e5285c3ccbbd570130f9ea4b81b00 is merged before and caused conflict. Could you rebase again? :)

**Review by sonmezonur — APPROVED** [review]

**Pull request merged**
